//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOARD_NOTICE
    {
        public decimal BOARD_IDX { get; set; }
        public string USERID { get; set; }
        public string EMAIL { get; set; }
        public string USERNM { get; set; }
        public string TITLE { get; set; }
        public string PASSWD { get; set; }
        public string WDATE { get; set; }
        public string UDATE { get; set; }
        public Nullable<decimal> COUNTS { get; set; }
        public string TAG { get; set; }
        public Nullable<decimal> RE_IDX { get; set; }
        public Nullable<decimal> RE_STEP { get; set; }
        public Nullable<decimal> RE_LEVEL { get; set; }
        public string CONTENT { get; set; }
        public string FNAME { get; set; }
        public string FSIZE { get; set; }
        public Nullable<decimal> FCOUNTS { get; set; }
        public string POPUP { get; set; }
        public string SDATE { get; set; }
        public string EDATE { get; set; }
        public string E_BUKRS { get; set; }
        public string E_WERKS { get; set; }
    }
}
